# -*- coding: utf-8 -*-
"""
Created on Tue Jan 22 23:43:40 2019

@author: Jairo Fernández Carmona
"""
"""
He decidido que voy a usar el 50% (657 personas) de los ejemplos proporcionados para el conjunto de entrenamiento, 
el 25% (328 personas) para el conjunto de validación y el 25% restante para el conjunto de test. 
Hay 322 pasajeros que viajaban en primera clase, 281 que viajaban en segunda clase y 710 personas que viajaban en tercera clase.
He observado que los pasajeros están ordenados por la clase en la que viajan y cuando la clase es la misma el criterio utilizado
es el orden alfabético de sus nombres. Por lo tanto creo que para hacer que los 3 conjuntos estén estratificados basta con elegir
un porcentaje de pasajeros de cada clase acorde a la dimensión del total de pasajeros.

Los pasajeros que viajaban en primera clase suponen un 24.5% del total, los de segunda un 21.4% y los de tercera un 54.1%.

Por tanto, para cada conjunto utilizaremos el siguiente número de pasajeros según la clase en la que viajaban:
    - Conjunto de entrenamiento: 162 pasajeros de 1ª clase, 139 pasajeros de 2ª clase y 356 pasajeros de 3ª clase, para un total de 657 pasajeros.
    - Conjunto de validación: 80 pasajeros de 1ª clase, 71 pasajeros de 2ª clase y 177 pasajeros de 3ª clase, total de 328 pasajeros.
    - Conjunto de test: 80 pasajeros de 1ª, 71 pasajeros de 2ª y 177 pasajeros de 3ª, total de 328.

Los 3 atributos que he elegido han sido:
    - Clase en la que viajaban: creo que el viajar en una determinada clase puede ser muy influyente ya que los camarotes se encontrarían
        en una zona específica del barco, supongo que los camarotes de más clase se encontrarían más arriba y los de menos más abajo y seguro que esto
        tuvo mucha influencia a la hora de desalojar a la gente del barco.
        
    - Edad: creo que puede ser un factor algo indicativo de la forma física que tendría la persona, además de suponer una prioridad ayudar a personas muy jóvenes
        o muy mayores que no pudieran valerse por sí mismas. Por ejemplo un recién nacido no podría valerse por sí mismo pero puede que los padres que acompañaran a este niño
        tuvieran prioridad para salir con él, antes que otro adulto que no acompañara a ningún niño.
        
    - Sexo: como he explicado con la edad creo que este factor es importante a la hora de observar si había alguna especie de prioridad a la hora de la evacuación. Por seguir con el ejemplo
        anterior, si hubiera que elegir un solo acompañante para un niño puede que la elegida fuese la madre antes que el padre.
        
Ya que voy a utilizar el atributo EDAD seguiré el procedimiento que se explica en el enunciado asignando a cada persona que no tenga una edad registrada la media aritmética del total de la edad del resto.

Para dividir los ejemplos en estos 3 conjuntos voy a realizar un método que lea todo el archivo y divida en una lista de 3 posiciones
cada conjunto, llevando la cuenta de cuantos pasajeros de cada clase lleva procesados para saber a qué conjunto debe añadirlos.

"""

"""
En este método lo único que voy a hacer será dar un pequeño formateo a cada una de las líneas, eliminando las comillas y los saltos
de línea y dividiré a los pasajeros en los 3 conjuntos.
"""

def creaConjuntos():
    fichero_titanic = open("titanic.txt","r")
    lista_conjuntos = [[],[],[]]
    
    for cont_linea,linea in enumerate(fichero_titanic):
        if cont_linea > 0: #Me salto la cabecera
            linea = linea.replace('\"','') #Elimino las comillas
            linea = linea.replace('\n', '') #Elimino los símbolos de salto de línea
            
            if ", jr" in linea:
                linea = linea.replace(", jr", "")
            if ", Jr" in linea:
                linea = linea.replace(", Jr", "")
            
            linea = linea.split(",") #Divido las líneas cada vez que hay comas
            
            #Como ya he explicado voy a guardar los 162 primeros pasajeros de la 1ª clase en el conj de entrenamiento, los 80 siguientes
            # en el conjunto de validación y los últimos 80 en el de test. Dependiendo de la clase yy el número de entrada lo guardaré en el conjunto correspondiente.
            # El conjunto de entrenamiento corresponde a la posición 0 de la lista_conjuntos, validación a la 1 y test a la 2.

            if(linea[1] == "1st"):
                if(len(lista_conjuntos[0]) < 162):
                    lista_conjuntos[0].append(linea)
                else:
                    if(len(lista_conjuntos[1]) < 80):
                        lista_conjuntos[1].append(linea)
                    else:
                        lista_conjuntos[2].append(linea)
                        
            else:
                if(linea[1] == "2nd"):
                    if(len(lista_conjuntos[0]) < 301):
                        lista_conjuntos[0].append(linea)
                    else:
                        if(len(lista_conjuntos[1]) < 151):
                            lista_conjuntos[1].append(linea)
                        else:
                            lista_conjuntos[2].append(linea)
                            
                else:
                    
                    if(len(lista_conjuntos[0]) < 657):
                        lista_conjuntos[0].append(linea)
                    else:
                        if(len(lista_conjuntos[1]) < 328):
                            lista_conjuntos[1].append(linea)
                        else:
                            lista_conjuntos[2].append(linea)
                            
    fichero_titanic.close()
                           
    return lista_conjuntos


"""
En este método voy a calcular la media aritmética de las edades de los pasajeros para luego (en otro método) insertar ese valor
en los pasajeros cuya edad no está registrada. Al ejecutar este método hemos descubierto que la edad media de los pasajeros
cuya edad está registrada es de 31 años, por lo tanto todo pasajero sin edad registrada tendrá un valor por defecto de "+",
que es el valor que le vamos a dar para indicar que tiene más de 13 años, el valor "-" indicará por el contrario que tiene
menos de 13 años.
"""
          
def calculaEdadMedia(lista_conjuntos):
    sumaEdades = 0 #Lo usamos para sumar todas las edades
    cont_pasajeros_edad = 0 #Lo usamos para contar el número de pasajeros que tienen registrada la edad
    
    for conjunto in lista_conjuntos:
        for pasajero in conjunto:
            #Ya que el archivo titanic.txt no sigue un formato fijo debo comprobar en qué posición de la lista está la edad.
            #Hay nombres que incluyen 2 o 3 comas, con las ciudades pasa lo mismo, el archivo no sigue un formato fijo, varía
            #dependiendo de si le añaden sufijos al nombre de la persona o especifican el estado/país de las ciudades.
            try:
                if(pasajero[5] != "NA"): #Comprobamos que el pasajero tiene una edad registrada
                    sumaEdades = sumaEdades + float(pasajero[5])
                    cont_pasajeros_edad = cont_pasajeros_edad +1
            except ValueError:
                try:
                    if(pasajero[6] != "NA"): #Comprobamos que el pasajero tiene una edad registrada
                        sumaEdades = sumaEdades + float(pasajero[6])
                        cont_pasajeros_edad = cont_pasajeros_edad +1
                except ValueError:
                    if(pasajero[4] != "NA"): #Comprobamos que el pasajero tiene una edad registrada
                        sumaEdades = sumaEdades + float(pasajero[4])
                        cont_pasajeros_edad = cont_pasajeros_edad +1
            
            
    return sumaEdades/cont_pasajeros_edad
    

"""
En este método voy a formatear los conjuntos para que queden como quiero, cada pasajero constará de la clase en la que viajaba
en la posición 0, la edad (como valor binario, si es mayor de 13 años o no) en la posición 1 ,el sexo en la posición 2 y
si sobrevivió como último valor.
"""

def formateaConjuntos(lista_conjuntos, edadMedia):
    conjuntos=[[],[],[]]
    datos_pasajero = [] #Lista con los datos del pasajero que quiero guardar
    
    for num_conjunto,conjunto in enumerate(lista_conjuntos):
        for pasajero in conjunto:
            
            datos_pasajero.append(pasajero[1])
            datos_pasajero.append(insertaEdad(pasajero))          
            datos_pasajero.append(pasajero[len(pasajero)-1])
            datos_pasajero.append(pasajero[2])
            
            if(num_conjunto == 0):#Si estamos revisando el conjunto 0 guardamos el pasajero en el conj 0 de la nueva lista
                conjuntos[0].append(datos_pasajero)
            else:
                if(num_conjunto == 1):
                    conjuntos[1].append(datos_pasajero)
                else:
                    conjuntos[2].append(datos_pasajero)
            
            datos_pasajero = [] #Reinicio el valor de la lista
    
    return conjuntos


"""
Este es un método auxiliar que utilizo para comprobar las edades de los pasajeros y asignarles su correspondiente valor positivo o negativo
"""


def insertaEdad(pasajero):
    valor_edad = "+"
 
    try:
        if(pasajero[4] != "NA"):#Si el pasajero tiene edad registrada comprobamos si es mayor o menor de 13 años
            if(float(pasajero[4]) <= 13):
                valor_edad = "-"
    except ValueError:
        try:
           if(pasajero[5] != "NA"):
               if(float(pasajero[5]) <= 13):
                   valor_edad = "-"
        except ValueError:
               if(pasajero[6] != "NA"):
                   if(float(pasajero[6]) <= 13):
                       valor_edad = "-" 
 
    return valor_edad


"""
En este último método lo único que voy a hacer es escribir en un nuevo fichero los 3 conjuntos que he creado, para poder pegarlos
con mayor facilidad en este archivo.
"""

def archivoConjuntos(conjuntos_formateados):
    archivo_conjuntos = open("conjuntos_titanic.txt", "w")
    
    for conjunto in conjuntos_formateados:
        for pasajero in conjunto:
            linea = str(pasajero)
            linea = linea+",\n"
            archivo_conjuntos.write(linea)
        archivo_conjuntos.write("\n")
        
    archivo_conjuntos.close()
    
#conjuntos_titanic = creaConjuntos()
#edad_media = calculaEdadMedia(conjuntos_titanic)
#conjuntos_formateados = formateaConjuntos(conjuntos_titanic, edad_media)
#archivoConjuntos(conjuntos_formateados)

"""
Al ejecutar los métodos de cobertura (en reglas.py) con los datos y conjuntos de este archivo he obtenido los siguientes resultados:
    - Sin poda (rendimiento sobre conjunto de test):
        * Si ( Sexo  =  female ) y ( Clase  =  1st ) y ( Edad  =  + ) entonces: [ Supervivencia  =  1]
        * Si ( Sexo  =  female ) y ( Clase  =  2nd ) y ( Edad  =  - ) entonces: [ Supervivencia  =  1]
        * Si ( Sexo  =  female ) y ( Clase  =  2nd ) y ( Edad  =  + ) entonces: [ Supervivencia  =  1]
        * Si ( Edad  =  - ) y ( Clase  =  2nd ) entonces: [ Supervivencia  =  1]
        * Si ( Sexo  =  female ) y ( Edad  =  + ) y ( Clase  =  3rd ) entonces: [ Supervivencia  =  1]
        * Si ( Edad  =  - ) y ( Clase  =  1st ) y ( Sexo  =  male ) entonces: [ Supervivencia  =  1]
        * Si ( Clase  =  1st ) y ( Edad  =  + ) y ( Sexo  =  male ) entonces: [ Supervivencia  =  1]
        * En caso contrario: [ Supervivencia  =  0 ]
        - Rendimiento sin poda:  0.7408536585365854
        
    - Con poda (rendimiento sobre conjunto de test):
        * Si ( Sexo  =  female ) entonces: [ Supervivencia  =  1]
        * Si ( Edad  =  - ) entonces: [ Supervivencia  =  1]
        * En caso contrario: [ Supervivencia  =  0 ]
        - Rendimiento con poda:  0.8140243902439024
        
Se observa con claridad que el rendimiento mejora al aplicar los algoritmos de poda, pasando de un 74.085% a un 81.402% de rendimiento.
Al fijarnos en las reglas podadas vemos que los atributos más importantes a la hora de decidir sobre la posible supervivencia
de un pasajero son el sexo y la edad (descartando la clase en la que viajaban), siendo las mujeres y los menores de 13 años los 
que componen un grupo mayoritario de los supervivientes.
        

Paso a escribir de la forma que se pedía los datos necesarios.
"""

atributo_clasificación = 'Supervivencia'

clases=['1','0']

atributos=[("Clase",['1st','2nd','3rd']),
           ("Edad",['+','-']),
           ("Sexo",['female','male'])]

entr=[['1st', '+', 'female', '1'],
['1st', '-', 'female', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '0'],
['1st', '-', 'male', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '-', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '-', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '-', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '-', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '-', 'female', '0'],
['3rd', '-', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '-', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '-', 'female', '0'],
['3rd', '-', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '-', 'male', '0'],
['3rd', '-', 'male', '0'],
['3rd', '-', 'male', '1'],
['3rd', '-', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '-', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '-', 'female', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '-', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '-', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '-', 'male', '1'],
['3rd', '-', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '-', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '-', 'male', '1'],
['3rd', '-', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '-', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '-', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '-', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '-', 'male', '0'],
['3rd', '-', 'female', '0'],
['3rd', '-', 'male', '0'],
['3rd', '-', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0']]

valid=[['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '-', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0']]

test=[['1st', '-', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'male', '0'],
['1st', '+', 'male', '0'],
['1st', '+', 'female', '1'],
['1st', '+', 'female', '0'],
['1st', '+', 'female', '0'],
['1st', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '-', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '-', 'female', '1'],
['2nd', '-', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '1'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'female', '0'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'female', '1'],
['2nd', '+', 'male', '0'],
['2nd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '1'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'male', '0'],
['3rd', '+', 'female', '0'],
['3rd', '+', 'male', '0']]
















